# Generated by Django 4.2 on 2023-08-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
    ]
