# Generated by Django 4.2.2 on 2023-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0005_proveedor_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='comentarios',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
