# Generated by Django 4.2.2 on 2023-09-07 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alta_proveedores', '0008_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de solicitudes de proveedor',
                'verbose_name_plural': 'historiales de solicitudes de proveedor',
            },
        ),
    ]
