# Generated by Django 4.2.2 on 2023-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0009_proveedorhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='es_migracion',
            field=models.BooleanField(default=False),
        ),
    ]
