# Generated by Django 4.2.2 on 2023-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0011_remove_proveedor_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
