# Generated by Django 4.2.2 on 2023-09-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0013_proveedor_empresa_destino_proveedor_empresa_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='otro_codigo_bancario',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='otro_codigo_bancario_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='swift',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='swift_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuenta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuenta_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
