# Generated by Django 4.2.2 on 2023-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0014_proveedor_otro_codigo_bancario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='es_migracion',
            field=models.BooleanField(),
        ),
    ]
