# Generated by Django 4.2.2 on 2023-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0015_alter_proveedor_es_migracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='es_migracion',
            field=models.BooleanField(default=False),
        ),
    ]
