# Generated by Django 4.2.2 on 2023-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0017_remove_proveedor_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='borrador',
            field=models.BooleanField(default=False),
        ),
    ]
