# Generated by Django 4.2.2 on 2023-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0018_proveedor_borrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Proveedor catálogo',
                'verbose_name_plural': 'Proveedores catálogo',
            },
        ),
    ]
