# Generated by Django 4.2 on 2023-10-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0019_catalogoproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dias_credito',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='limite_credito_ME',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='limite_credito_MN',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='monto_credito',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
