# Generated by Django 4.2 on 2023-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0020_alter_proveedor_dias_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='limite_credito_ME',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='limite_credito_MN',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='monto_credito',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
