# Generated by Django 4.2 on 2023-10-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0026_alter_proveedor_constancia_situacion_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='constancia_situacion_fiscal',
            field=models.FileField(blank=True, upload_to='static/documentos/constancias'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado_cuenta_bancario',
            field=models.FileField(blank=True, upload_to='static/documentos/estados_cuenta'),
        ),
    ]
