# Generated by Django 4.2 on 2023-10-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0027_alter_proveedor_constancia_situacion_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='regimen_capital',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
