# Generated by Django 4.2 on 2023-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0028_alter_proveedor_regimen_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
