# Generated by Django 4.2 on 2023-10-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0029_alter_proveedor_nombre_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoproveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogoproveedor',
            name='nombre_comercial',
            field=models.CharField(max_length=100),
        ),
    ]
