# Generated by Django 4.2 on 2023-10-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0030_alter_catalogoproveedor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='banco_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
