# Generated by Django 4.2 on 2023-10-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0031_alter_proveedor_banco_alter_proveedor_banco_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='limite_credito_ME',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='limite_credito_MN',
        ),
    ]
