# Generated by Django 4.2 on 2023-10-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0032_remove_proveedor_limite_credito_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='constancia_situacion_fiscal',
            field=models.FileField(blank=True, upload_to='static/proveedores/constancias'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado_cuenta_bancario',
            field=models.FileField(blank=True, upload_to='static/proveedores/estados_cuenta'),
        ),
    ]
