# Generated by Django 4.2 on 2023-10-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0033_alter_proveedor_constancia_situacion_fiscal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='monto_credito',
            new_name='monto_credito_mn',
        ),
    ]
