# Generated by Django 4.2 on 2023-10-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0035_proveedor_monto_credito_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
