# Generated by Django 4.2 on 2023-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0036_alter_proveedor_telefono_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fair_trade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
