# Generated by Django 4.2 on 2023-12-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0038_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
