# Generated by Django 4.2 on 2024-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0039_delete_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
