# Generated by Django 4.2 on 2024-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0040_alter_proveedor_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('mercado', models.CharField(blank=True, max_length=50)),
                ('tiempo_llegada', models.CharField(blank=True, max_length=20)),
                ('codigo_alterno', models.CharField(blank=True, max_length=50)),
                ('consignatario', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=14)),
                ('contacto', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('colonia', models.CharField(blank=True, max_length=50)),
                ('numero_exterior', models.CharField(blank=True, max_length=20)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20)),
                ('nombre_comex', models.CharField(blank=True, max_length=30)),
                ('calle_comex', models.CharField(blank=True, max_length=100)),
                ('id_fiscal_comex', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'lugar de destino',
                'verbose_name_plural': 'lugares de destino',
            },
        ),
    ]
