# Generated by Django 4.2 on 2024-04-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_proveedores', '0041_destinationplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationplace',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='id_solicitud',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_solicitud',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
