EMPRESA_LIST = [
    ('', 'Seleccione una opción'),
    ('Sonorg', 'Sonorg'),
    ('Tago', 'Tago'),
    ('Wichita', 'Wichita'),
    ('Moonrise', 'Moonrise'),
    ('Wellin', 'Wellin'),
    ('Sonorg - Tago', 'Sonorg - Tago'),
    ('Sonorg - Wichita', 'Sonorg - Wichita'),
    ('Tago - Wichita', 'Tago - Wichita'),
    ('Sonorg - Tago - Wichita', 'Sonorg - Tago - Wichita'),
    ('Moonrise - Wellin', 'Moonrise - Wellin'),
]

TIPO_ALTA_LIST = [
    ('', 'Seleccione una opción'),
    ('Proveedor', 'Proveedor'),
    ('Cliente', 'Cliente'),
]

CONTRIBUYENTE_LIST = [
    ('', 'Seleccione una opción'),
    ('Persona física', 'Persona física'),
    ('Persona moral', 'Persona moral'),
]

REGIMEN_CAPITAL_LIST = [
    ('', 'Seleccione una opción'),
    ('ASOCIACION RURAL DE INTERES COLECTIVO DE CAPITAL VARIABLE - A.R. de I.C. de C.V.', 'ASOCIACION RURAL DE INTERES COLECTIVO DE CAPITAL VARIABLE - A.R. de I.C. de C.V.'),
    ('ASOCIACION DE BENEFICENCIA PRIVADA - A. de B.P.', 'ASOCIACION DE BENEFICENCIA PRIVADA - A. de B.P.'),
    ('ASOCIACION EN PARTICIPACION - A. en P.', 'ASOCIACION EN PARTICIPACION - A. en P.'),
    ('ASOCIACION AGRICOLA - A.A.', 'ASOCIACION AGRICOLA - A.A.'),
    ('ASOCIACION CIVIL - A.C.', 'ASOCIACION CIVIL - A.C.'),
    ('ASOCIACION GANADERA - A.G.', 'ASOCIACION GANADERA - A.G.'),
    ('ASOCIACION LOCAL DE PRODUCTORES RURALES - A.L. de P.R.', 'ASOCIACION LOCAL DE PRODUCTORES RURALES - A.L. de P.R.'),
    ('AGRUPACION POLITICA ESTATAL - A.P.E.', 'AGRUPACION POLITICA ESTATAL - A.P.E.'),
    ('AGRUPACION POLITICA LOCAL - A.P.L.', 'AGRUPACION POLITICA LOCAL - A.P.L.'),
    ('AGRUPACION POLITICA NACIONAL - A.P.N.', 'AGRUPACION POLITICA NACIONAL - A.P.N.'),
    ('ASOCIACION RELIGIOSA - A.R.', 'ASOCIACION RELIGIOSA - A.R.'),
    ('ASOCIACIONES RURALES DE INTERES COLECTIVO - A.R. de I.C.', 'ASOCIACIONES RURALES DE INTERES COLECTIVO - A.R. de I.C.'),
    ('ASOCIACION RURAL DE INTERES COLECTIVO DE CAPITAL VARIABLE DE RESPONSABILIDAD IMITADA - A.R. de I.C. de C.V.', 'ASOCIACION RURAL DE INTERES COLECTIVO DE CAPITAL VARIABLE DE RESPONSABILIDAD IMITADA - A.R. de I.C. de C.V.'),
    ('ASOCIACION RURAL DE INTERES COLECTIVO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - A.R. de I.C. de L. de C.V.', 'ASOCIACION RURAL DE INTERES COLECTIVO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - A.R. de I.C. de L. de C.V.'),
    ('ASOCIACION RURAL DE INTERES COLECTIVO DE RESPONSABILIDAD ILIMITADA - A.R. de I.C. de R.I.', 'ASOCIACION RURAL DE INTERES COLECTIVO DE RESPONSABILIDAD ILIMITADA - A.R. de I.C. de R.I.'),
    ('ASOCIACION RURAL DE INTERES COLECTIVO DE RESPONSABILIDAD LIMITADA - A.R. de I.C. de R.L.', 'ASOCIACION RURAL DE INTERES COLECTIVO DE RESPONSABILIDAD LIMITADA - A.R. de I.C. de R.L.'),
    ('COMPANIA POR ACCIONES - C. por A.', 'COMPANIA POR ACCIONES - C. por A.'),
    ('COOPERATIVA ESCOLAR LIMITADA - C.E.L.', 'COOPERATIVA ESCOLAR LIMITADA - C.E.L.'),
    ('EMPRESA FILIAL - E.F.', 'EMPRESA FILIAL - E.F.'),
    ('EMPRESA MICROINDUSTRIAL - E.M.', 'EMPRESA MICROINDUSTRIAL - E.M.'),
    ('EMPRESA PRODUCTIVA DEL ESTADO - E.P. del E.', 'EMPRESA PRODUCTIVA DEL ESTADO - E.P. del E.'),
    ('EMPRESA PRODUCTIVA SUBSIDIARIA - E.P.S.', 'EMPRESA PRODUCTIVA SUBSIDIARIA - E.P.S.'),
    ('FONDO DE ASEGURAMIENTO - F. de A.', 'FONDO DE ASEGURAMIENTO - F. de A.'),
    ('FEDERACION DE COOPERATIVAS DE RESPONSABILIDAD LIMITADA - F. de C de R. L.', 'FEDERACION DE COOPERATIVAS DE RESPONSABILIDAD LIMITADA - F. de C de R. L.'),
    ('FEDERACION DE COOPERATIVAS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - F. de C de R. L. de C.V.', 'FEDERACION DE COOPERATIVAS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - F. de C de R. L. de C.V.'),
    ('FUNDACION - Fund.', 'FUNDACION - Fund'),
    ('INSTITUCION DE ASISTENCIA SOCIAL - I. de A.P.', 'INSTITUCION DE ASISTENCIA SOCIAL - I. de A.P.'),
    ('INSTITUCION DE ASISTENCIA SOCIAL PRIVADA - I. de A.S.', 'INSTITUCION DE ASISTENCIA SOCIAL PRIVADA - I. de A.S.'),
    ('INSTITUCION DE BENEFICENCIA PRIVADA - I. de A.S.P.', 'INSTITUCION DE BENEFICENCIA PRIVADA - I. de A.S.P.'),
    ('INSTITUCION DE ASISTENCIA PRIVADA - I.A.P.', 'INSTITUCION DE ASISTENCIA PRIVADA - I.A.P.'),
    ('PRODUCCION DE ARTESANIAS - P. de A.', 'PRODUCCION DE ARTESANIAS - P. de A.'),
    ('PROPIEDAD EN CONDOMINIO - P. en C.', 'PROPIEDAD EN CONDOMINIO - P. en C.'),
    ('RESPONSABILIDAD ILIMITADA - R.I.', 'RESPONSABILIDAD ILIMITADA - R.I.'),
    ('RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - R.L. de C.V.', 'RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - R.L. de C.V.'),
    ('RESPONSABILIDAD LIMITADA Y CAPITAL VARIABLE - R.L. y C.V.', 'RESPONSABILIDAD LIMITADA Y CAPITAL VARIABLE - R.L. y C.V.'),
    ('SOCIEDAD DE CAPITAL VARIABLE - S. de C.V.', 'SOCIEDAD DE CAPITAL VARIABLE - S. de C.V.'),
    ('SOCIEDAD DE GESTION COLECTIVA - S. de G.C.', 'SOCIEDAD DE GESTION COLECTIVA - S. de G.C.'),
    ('SOCIEDAD DE INVERSION DE OBJETO LIMITADO - S. de I. de O.L.', 'SOCIEDAD DE INVERSION DE OBJETO LIMITADO - S. de I. de O.L.'),
    ('SOCIEDAD DE PRODUCCION DE RESPONSABILIDAD LIMITADA - S. de P. de R.L.', 'SOCIEDAD DE PRODUCCION DE RESPONSABILIDAD LIMITADA - S. de P. de R.L.'),
    ('SOCIEDAD DE PRODUCCION DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de P. de R.L. de C.V.', 'SOCIEDAD DE PRODUCCION DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de P. de R.L. de C.V.'),
    ('SOCIEDAD DE PRODUCCION AGRICOLA DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de P.A. de R.L. de C.V.', 'SOCIEDAD DE PRODUCCION AGRICOLA DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de P.A. de R.L. de C.V.'),
    ('SOCIEDAD DE PRODUCCION RURAL - S. de P.R.', 'SOCIEDAD DE PRODUCCION RURAL - S. de P.R.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE CAPITAL VARIABLE - S. de P.R. de C.V.', 'SOCIEDAD DE PRODUCCION RURAL DE CAPITAL VARIABLE - S. de P.R. de C.V.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE CAPITAL VARIABLE DE RESPONSABILIDAD ILIMITADA - S. de P.R. de C.V. de R.I.', 'SOCIEDAD DE PRODUCCION RURAL DE CAPITAL VARIABLE DE RESPONSABILIDAD ILIMITADA - S. de P.R. de C.V. de R.I.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA - S. de P.R. de R.I.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA - S. de P.R. de R.I.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S. de P.R. de R.I. de C.V.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S. de P.R. de R.I. de C.V.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA - S. de P.R. de R.L.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA - S. de P.R. de R.L.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de P.R. de R.L. de C.V.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de P.R. de R.L. de C.V.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD SOLIDARIA ILIMITADA - S. de P.R. de R.S.I.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD SOLIDARIA ILIMITADA - S. de P.R. de R.S.I.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD SUPLEMENTADA - S. de P.R.S.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD SUPLEMENTADA - S. de P.R.S.'),
    ('SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S. de P.R.S. de C.V.', 'SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S. de P.R.S. de C.V.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de R.L de C.V.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. de R.L de C.V.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE MICROINDUSTRIAL - S. de R.L de C.V.M.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE MICROINDUSTRIAL - S. de R.L de C.V.M.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO - S. de R.L de I.P.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO - S. de R.L de I.P.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO DE CAPITAL VARIABLE - S. de R.L de I.P. de C.V.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO DE CAPITAL VARIABLE - S. de R.L de I.P. de C.V.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO Y CAPITAL VARIABLE - S. de R.L de I.P. y C.V.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO Y CAPITAL VARIABLE - S. de R.L de I.P. y C.V.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA - S. de R.L.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA - S. de R.L.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA ARTESANAL - S. de R.L.A.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA ARTESANAL - S. de R.L.A.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL - S. de R.L.M.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL - S. de R.L.M.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL DE CAPITAL VARIABLE - S. de R.L.M. de C.V.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL DE CAPITAL VARIABLE - S. de R.L.M. de C.V.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL ARTESANAL - S. de R.L.M.A.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL ARTESANAL - S. de R.L.M.A.'),
    ('SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL ARTESANAL DE CAPITAL VARIABLE - S. de R.L.M.A. de C.V.', 'SOCIEDAD DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL ARTESANAL DE CAPITAL VARIABLE - S. de R.L.M.A. de C.V.'),
    ('SOCIEDAD DE SOLIDARIDAD SOCIAL - S. de S.S.', 'SOCIEDAD DE SOLIDARIDAD SOCIAL - S. de S.S.'),
    ('SOCIEDAD DE SOLIDARIDAD SOCIAL DE RESPONSABILIDAD ILIMITADA - S. de S.S. de R.I.', 'SOCIEDAD DE SOLIDARIDAD SOCIAL DE RESPONSABILIDAD ILIMITADA - S. de S.S. de R.I.'),
    ('SOCIEDAD DE SOLIDARIDAD SOCIAL DE RESPONSABILIDAD LIMITADA - S. de S.S. de R.L.', 'SOCIEDAD DE SOLIDARIDAD SOCIAL DE RESPONSABILIDAD LIMITADA - S. de S.S. de R.L.'),
    ('SOCIEDAD EN COMANDITA POR ACCIONES - S. en C. por A.', 'SOCIEDAD EN COMANDITA POR ACCIONES - S. en C. por A.'),
    ('SOCIEDAD EN COMANDITA POR ACCIONES DE CAPITAL VARIABLE - S. en C. por A. de C.V.', 'SOCIEDAD EN COMANDITA POR ACCIONES DE CAPITAL VARIABLE - S. en C. por A. de C.V.'),
    ('SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD ILIMITADA - S. en C. por A. de R.I.', 'SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD ILIMITADA - S. en C. por A. de R.I.'),
    ('SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S. en C. por A. de R.I. de C.V.', 'SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S. en C. por A. de R.I. de C.V.'),
    ('SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD LIMITADA - S. en C. por A. de R.L.', 'SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD LIMITADA - S. en C. por A. de R.L.'),
    ('SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. en C. por A. de R.L. de C.V.', 'SOCIEDAD EN COMANDITA POR ACCIONES DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. en C. por A. de R.L. de C.V.'),
    ('SOCIEDAD EN COMANDITA SIMPLE - S. en C.S.', 'SOCIEDAD EN COMANDITA SIMPLE - S. en C.S.'),
    ('SOCIEDAD EN COMANDITA SIMPLE DE CAPITAL VARIABLE - S. en C.S. de C.V.', 'SOCIEDAD EN COMANDITA SIMPLE DE CAPITAL VARIABLE - S. en C.S. de C.V.'),
    ('SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD ILIMITADA - S. en C.S. de R.I.', 'SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD ILIMITADA - S. en C.S. de R.I.'),
    ('SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S. en C.S. de R.I. de C.V.', 'SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S. en C.S. de R.I. de C.V.'),
    ('SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD LIMITADA - S. en C.S. de R.L.', 'SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD LIMITADA - S. en C.S. de R.L.'),
    ('SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. en C.S. de R.L. de C.V.', 'SOCIEDAD EN COMANDITA SIMPLE DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S. en C.S. de R.L. de C.V.'),
    ('SOCIEDAD EN NOMBRE COLECTIVO - S. en N.C.', 'SOCIEDAD EN NOMBRE COLECTIVO - S. en N.C.'),
    ('SOCIEDAD EN NOMBRE COLECTIVO DE CAPITAL VARIABLE - S. en N.C. de C.V.', 'SOCIEDAD EN NOMBRE COLECTIVO DE CAPITAL VARIABLE - S. en N.C. de C.V.'),
    ('SOCIEDAD EN NOMBRE COLECTIVA DE RESPONSABILIDAD ILIMITADA - S. en N.C. de R.I.', 'SOCIEDAD EN NOMBRE COLECTIVA DE RESPONSABILIDAD ILIMITADA - S. en N.C. de R.I.'),
    ('SOCIEDAD EN NOMBRE COLECTIVO DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE (*) - S. en N.C. de R.I. de C.V.', 'SOCIEDAD EN NOMBRE COLECTIVO DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE (*) - S. en N.C. de R.I. de C.V.'),
    ('SOCIEDAD EN NOMBRE COLECTIVO DE RESPONSABILIDAD LIMITADA - S. en N.C. de R.L.', 'SOCIEDAD EN NOMBRE COLECTIVO DE RESPONSABILIDAD LIMITADA - S. en N.C. de R.L.'),
    ('SOCIEDAD EN NOMBRE COLECTIVO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE (*) - S. en N.C. de R.L. de C.V.', 'SOCIEDAD EN NOMBRE COLECTIVO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE (*) - S. en N.C. de R.L. de C.V.'),
    ('SOCIEDAD FINANCIERA COMUNITARIA - S. financiera C.', 'SOCIEDAD FINANCIERA COMUNITARIA - S. financiera C.'),
    ('SOCIEDAD ANONIMA - S.A.', 'SOCIEDAD ANONIMA - S.A.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE - S.A. de C.V.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE - S.A. de C.V.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION DE CAPITALES - S.A. de C.V.S. de I. de C.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION DE CAPITALES - S.A. de C.V.S. de I. de C.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION EN INSTRUMENTOS DE DEUDA - S.A. de C.V.S. de I. de I. de D.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION EN INSTRUMENTOS DE DEUDA - S.A. de C.V.S. de I. de I. de D.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION EN INSTRUMENTOS DE DEUDA PARA PERSONAS MO - S.A. de C.V.S. de I. de I. de D.P.P.MO.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION EN INSTRUMENTOS DE DEUDA PARA PERSONAS MO - S.A. de C.V.S. de I. de I. de D.P.P.MO.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION DE RENTA VARIABLE - S.A. de C.V.S. de I. de R.V.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DE INVERSION DE RENTA VARIABLE - S.A. de C.V.S. de I. de R.V.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DISTRIBUIDORA INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSION S.A. de C.V.S.D.I. de A. de S. de I.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD DISTRIBUIDORA INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSION S.A. de C.V.S.D.I. de A. de S. de I.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO LIMITADO - S.A. de C.V.S.F. de O.L.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO LIMITADO - S.A. de C.V.S.F. de O.L.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A. de C.V.S.F. de O.M.E. no R.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A. de C.V.S.F. de O.M.E. no R.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD REGULADA - S.A. de C.V.S.F. de O.M.E.R.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD REGULADA - S.A. de C.V.S.F. de O.M.E.R.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA COMUNITARIA - S.A. de C.V.S.F.C.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA COMUNITARIA - S.A. de C.V.S.F.C.'),
    ('SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA POPULAR - S.A. de C.V.S.F.P.', 'SOCIEDAD ANONIMA DE CAPITAL VARIABLE SOCIEDAD FINANCIERA POPULAR - S.A. de C.V.S.F.P.'),
    ('SOCIEDAD ANONIMA DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S.A. de R.I de C.V.', 'SOCIEDAD ANONIMA DE RESPONSABILIDAD ILIMITADA DE CAPITAL VARIABLE - S.A. de R.I de C.V.'),
    ('SOCIEDAD ANONIMA DE RESPONSABILIDAD ILIMITADA - S.A. de R.I.', 'SOCIEDAD ANONIMA DE RESPONSABILIDAD ILIMITADA - S.A. de R.I.'),
    ('SOCIEDAD ANONIMA DE RESPONSABILIDAD LIMITADA - S.A. de R.L.', 'SOCIEDAD ANONIMA DE RESPONSABILIDAD LIMITADA - S.A. de R.L.'),
    ('SOCIEDAD ANONIMA DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.A. de R.L. de C.V.', 'SOCIEDAD ANONIMA DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.A. de R.L. de C.V.'),
    ('SOCIEDAD ANONIMA SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A. SOFOM E.N.R.', 'SOCIEDAD ANONIMA SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A. SOFOM E.N.R.'),
    ('SOCIEDAD ANONIMA SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD REGULADA - S.A. SOFOM E.R.', 'SOCIEDAD ANONIMA SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD REGULADA - S.A. SOFOM E.R.'),
    ('SOCIEDAD ANONIMA BURSATIL - S.A.B.', 'SOCIEDAD ANONIMA BURSATIL - S.A.B.'),
    ('SOCIEDAD ANONIMA BURSATIL DE CAPITAL VARIABLE - S.A.B. de C.V.', 'SOCIEDAD ANONIMA BURSATIL DE CAPITAL VARIABLE - S.A.B. de C.V.'),
    ('SOCIEDAD ANONIMA PROMOTORA DE INVERSION - S.A.P.I.', 'SOCIEDAD ANONIMA PROMOTORA DE INVERSION - S.A.P.I.'),
    ('SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE - S.A.P.I. de C.V.', 'SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE - S.A.P.I. de C.V.'),
    ('SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A.P.I. de C.V. SOFOM E.N.R.', 'SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A.P.I. de C.V. SOFOM E.N.R.'),
    ('SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD REGULADA - S.A.P.I. de C.V. SOFOM E.R.', 'SOCIEDAD ANONIMA PROMOTORA DE INVERSION DE CAPITAL VARIABLE SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD REGULADA - S.A.P.I. de C.V. SOFOM E.R.'),
    ('SOCIEDAD ANONIMA PROMOTORA DE INVERSION SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A.P.I. SOFOM E.N.R.', 'SOCIEDAD ANONIMA PROMOTORA DE INVERSION SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - S.A.P.I. SOFOM E.N.R.'),
    ('SOCIEDAD ANONIMA PROMOTORA DE INVERSION BURSATIL DE CAPITAL VARIABLE - S.A.P.I.B. de C.V.', 'SOCIEDAD ANONIMA PROMOTORA DE INVERSION BURSATIL DE CAPITAL VARIABLE - S.A.P.I.B. de C.V.'),
    ('SOCIEDAD POR ACCIONES SIMPLIFICADA - S.A.S.', 'SOCIEDAD POR ACCIONES SIMPLIFICADA - S.A.S.'),
    ('SOCIEDAD POR ACCIONES SIMPLIFICADA DE CAPITAL VARIABLE - S.A.S. de C.V.', 'SOCIEDAD POR ACCIONES SIMPLIFICADA DE CAPITAL VARIABLE - S.A.S. de C.V.'),
    ('SOCIEDAD CIVIL - S.C.', 'SOCIEDAD CIVIL - S.C.'),
    ('SOCIEDAD COOPERATIVA DE AHORRO Y PRESTAMOS - S.C. de A. y P.', 'SOCIEDAD COOPERATIVA DE AHORRO Y PRESTAMOS - S.C. de A. y P.'),
    ('SOCIEDAD COOPERATIVA DE AHORRO Y PRESTAMO DE RESPONSABILIDAD LIMITADA - S.C. de A. y P. de R.L.', 'SOCIEDAD COOPERATIVA DE AHORRO Y PRESTAMO DE RESPONSABILIDAD LIMITADA - S.C. de A. y P. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE AHORRO Y PRESTAMO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de A. y P. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE AHORRO Y PRESTAMO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de A. y P. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de C. de B. y S. de R.L de C.V.', 'SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de C. de B. y S. de R.L de C.V.'),
    ('SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD LIMITADA - S.C. de C. de R.L.', 'SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD LIMITADA - S.C. de C. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD SUPLEMENTADA - S.C. de C. de R.S.', 'SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD SUPLEMENTADA - S.C. de C. de R.S.'),
    ('SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S.C. de C. de R.S. de C.V.', 'SOCIEDAD COOPERATIVA DE CONSUMO DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S.C. de C. de R.S. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE CAPITAL VARIABLE - S.C. de C.V.', 'SOCIEDAD COOPERATIVA DE CAPITAL VARIABLE - S.C. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE CAPITAL VARIABLE DE RESPONSABILIDAD LIMITADA - S.C. de C.V. de R.L.', 'SOCIEDAD COOPERATIVA DE CAPITAL VARIABLE DE RESPONSABILIDAD LIMITADA - S.C. de C.V. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION - S.C. de P.', 'SOCIEDAD COOPERATIVA DE PRODUCCION - S.C. de P.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE BIENES Y SERVICIOS DE RESPONSABILIDAD LIMITADA - S.C. de P. de B. y S. de R.L.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE BIENES Y SERVICIOS DE RESPONSABILIDAD LIMITADA - S.C. de P. de B. y S. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE BIENES Y SERVICIOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. de B. y S. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE BIENES Y SERVICIOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. de B. y S. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD LIMITADA - S.C. de P. de R.L.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD LIMITADA - S.C. de P. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD SUPLEMENTADA - S.C. de P. de R.S.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD SUPLEMENTADA - S.C. de P. de R.S.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S.C. de P. de R.S. de C.V.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S.C. de P. de R.S. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION DE SERVICIOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. de S. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE PRODUCCION DE SERVICIOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. de S. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA - S.C. de P. R. de R.L.', 'SOCIEDAD COOPERATIVA DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA - S.C. de P. R. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. R. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. R. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE PRODUCCION Y CONSUMO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. y C. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE PRODUCCION Y CONSUMO DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de P. y C. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD ILIMITADA - S.C. de R.I.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD ILIMITADA - S.C. de R.I.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA - S.C. de R.L.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA - S.C. de R.L.'),
    ('SOCIEDAD CIVIL DE RESPONSABILIDAD LIMITADA - S.C. de R.L.', 'SOCIEDAD CIVIL DE RESPONSABILIDAD LIMITADA - S.C. de R.L.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de R.L. de C.V.'),
    ('SOCIEDAD CIVIL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de R.L. de C.V.', 'SOCIEDAD CIVIL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO Y CAPITAL VARIABLE - S.C. de R.L. de I.P. y C.V.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA DE INTERES PUBLICO Y CAPITAL VARIABLE - S.C. de R.L. de I.P. y C.V.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL - S.C. de R.L. M.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD LIMITADA MICROINDUSTRIAL - S.C. de R.L. M.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD SUPLEMENTADA - S.C. de R.S.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD SUPLEMENTADA - S.C. de R.S.'),
    ('SOCIEDAD COOPERATIVA DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S.C. de R.S. de C.V.', 'SOCIEDAD COOPERATIVA DE RESPONSABILIDAD SUPLEMENTADA DE CAPITAL VARIABLE - S.C. de R.S. de C.V.'),
    ('SOCIEDAD COOPERATIVA DE SERVICIOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de S. de R.L. de C.V.', 'SOCIEDAD COOPERATIVA DE SERVICIOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - S.C. de S. de R.L. de C.V.'),
    ('SOCIEDAD COOPERATIVA LIMITADA - S.C.L.', 'SOCIEDAD COOPERATIVA LIMITADA - S.C.L.'),
    ('SOCIEDAD COOPERATIVA LIMITADA DE CAPITAL VARIABLE - S.C.L. de C.V.', 'SOCIEDAD COOPERATIVA LIMITADA DE CAPITAL VARIABLE - S.C.L. de C.V.'),
    ('SOCIEDAD CIVIL PARTICULAR - S.C.P.', 'SOCIEDAD CIVIL PARTICULAR - S.C.P.'),
    ('SOCIEDAD COOPERATIVA SUPLENTADA - S.C.S.', 'SOCIEDAD COOPERATIVA SUPLENTADA - S.C.S.'),
    ('SOCIEDAD CIVIL UNIVERSAL - S.C.U.', 'SOCIEDAD CIVIL UNIVERSAL - S.C.U.'),
    ('SOCIEDAD LIMITADA - S.L.', 'SOCIEDAD LIMITADA - S.L.'),
    ('SOCIEDAD NACIONAL DE CREDITO - S.N. de C.', 'SOCIEDAD NACIONAL DE CREDITO - S.N. de C.'),
    ('SIN TIPO DE SOCIEDAD - S.T. de S.', 'SIN TIPO DE SOCIEDAD - S.T. de S.'),
    ('SA PROMOTORA DE INVERSION DE CV SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - SA.P. de I. de C.V.', 'SA PROMOTORA DE INVERSION DE CV SOCIEDAD FINANCIERA DE OBJETO MULTIPLE ENTIDAD NO REGULADA - SA.P. de I. de C.V.'),
    ('UNION DE COMUNIDADES - U. de C.', 'UNION DE COMUNIDADES - U. de C.'),
    ('UNION DE COOPERATIVAS DE RESPONSABILIDAD LIMITADA Y DE CAPITAL VARIABLE - U. de C. de R.l. y de C.V.', 'UNION DE COOPERATIVAS DE RESPONSABILIDAD LIMITADA Y DE CAPITAL VARIABLE - U. de C. de R.l. y de C.V.'),
    ('UNION DE EJIDOS - U. de E.', 'UNION DE EJIDOS - U. de E.'),
    ('UNION DE EJIDOS DE RESPONSABILIDAD LIMITADA - U. de E. de R.L.', 'UNION DE EJIDOS DE RESPONSABILIDAD LIMITADA - U. de E. de R.L.'),
    ('UNION DE EJIDOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - U. de E. de R.L. de C.V.', 'UNION DE EJIDOS DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - U. de E. de R.L. de C.V.'),
    ('UNION DE SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA - U. de S. de P.R. de R.I.', 'UNION DE SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD ILIMITADA - U. de S. de P.R. de R.I.'),
    ('UNION DE SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA - U. de S. de P.R. de R.L.', 'UNION DE SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA - U. de S. de P.R. de R.L.'),
    ('UNION DE SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - U. de S. de P.R. de R.L. de C.V.', 'UNION DE SOCIEDAD DE PRODUCCION RURAL DE RESPONSABILIDAD LIMITADA DE CAPITAL VARIABLE - U. de S. de P.R. de R.L. de C.V.'),
    ('UNION DE SOCIEDADES DE PRODUCCION RURAL DE RESPONSABILIDAD SUPLEMENTADA - U. de S. de P.R. de R.S.', 'UNION DE SOCIEDADES DE PRODUCCION RURAL DE RESPONSABILIDAD SUPLEMENTADA - U. de S. de P.R. de R.S.'),
    ('UNIDAD ECONOMICA - U.E', 'UNIDAD ECONOMICA - U.E'),
]

REGIMEN_FISCAL_LIST = [
    ('', 'Seleccione una opción'),
    ('605 - Sueldos y Salarios e Ingresos Asimilados a Salarios', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'),
    ('606 - Arrendamiento', '606 - Arrendamiento'),
    ('608 - Demas Ingresos', '608 - Demas Ingresos'),
    ('611 - Ingresos por Dividendos (socios y accionistas)', '611 - Ingresos por Dividendos (socios y accionistas)'),
    ('612 - Personas Físicas con Actividades Empresariales y Profesionales', '612 - Personas Físicas con Actividades Empresariales y Profesionales'),
    ('614 - Ingresos por intereses', '614 - Ingresos por intereses'),
    ('616 - Sin obligaciones fiscales', '616 - Sin obligaciones fiscales'),
    ('621 - Incorporación Fiscal', '621 - Incorporación Fiscal'),
    ('629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', '629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales'),
    ('630 - Enajenación de acciones en bolsa de valores', '630 - Enajenación de acciones en bolsa de valores'),
    ('615 - Régimen de los ingresos por obtención de premios', '615 - Régimen de los ingresos por obtención de premios'),
    ('625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'),
    ('626 - Régimen Simplificado de Confianza', '626 - Régimen Simplificado de Confianza'),
    ('601 - General de Ley Personas Morales', '601 - General de Ley Personas Morales'),
    ('603 - Personas Morales con Fines no Lucrativos', '603 - Personas Morales con Fines no Lucrativos'),
    ('609 - Consolidación', '609 - Consolidación'),
    ('620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'),
    ('622 - Actividades Agrícolas', '622 - Actividades Agrícolas'),
    ('623 - Opcional para Grupos de Sociedades', '623 - Opcional para Grupos de Sociedades'),
    ('624 - Coordinados', '624 - Coordinados'),
    ('628 - Hidrocarburos', '628 - Hidrocarburos'),
    ('607 - Régimen de Enajenación o Adquisición de Bienes', '607 - Régimen de Enajenación o Adquisición de Bienes'),
    ('626 - Régimen Simplificado de Confianza', '626 - Régimen Simplificado de Confianza'),
    ('610 - Residentes en el Extranjero sin Establecimiento Permanente en México', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'),
]

USO_CFDI_LIST = [
    ('', 'Seleccione una opción'),
    ('G01 - Adquisición de Mercancías', 'G01 - Adquisición de Mercancías'),
    ('G02 - Devoluciones', 'G02 - Devoluciones'),
    ('G03 - Gastos en general', 'G03 - Gastos en general'),
    ('I01 - Construcciones', 'I01 - Construcciones'),
    ('I02 - Mobiliario y equipo de oficina por inversiones', 'I02 - Mobiliario y equipo de oficina por inversiones'),
    ('I03 - Equipo de transporte', 'I03 - Equipo de transporte'),
    ('I04 - Equipo de computo y accesorios', 'I04 - Equipo de computo y accesorios'),
    ('I05 - Dados', 'I05 - Dados'),
    ('I06 - Comunicaciones telefónicas', 'I06 - Comunicaciones telefónicas'),
    ('I07 - Comunicaciones satelitales', 'I07 - Comunicaciones satelitales'),
    ('I08 - Otra maquinaria y equipo', 'I08 - Otra maquinaria y equipo'),
    ('D01 - Honorarios médicos', 'D01 - Honorarios médicos'),
    ('D02 - Gastos médicos por incapacidad o discapacidad', 'D02 - Gastos médicos por incapacidad o discapacidad'),
    ('D03 - Gastos funerales', 'D03 - Gastos funerales'),
    ('D04 - Donativos', 'D04 - Donativos'),
    ('D05 - Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)', 'D05 - Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'),
    ('D06 - Aportaciones voluntarias al SAR', 'D06 - Aportaciones voluntarias al SAR'),
    ('D07 - Primas por seguros de gastos médicos', 'D07 - Primas por seguros de gastos médicos'),
    ('D08 - Gastos de transportación escolar obligatoria', 'D08 - Gastos de transportación escolar obligatoria'),
    ('D09 - Depósitos en cuentas para el ahorro', 'D09 - Depósitos en cuentas para el ahorro'),
    ('D10 - Pagos por servicios educativos (colegiaturas)', 'D10 - Pagos por servicios educativos (colegiaturas)'),
    ('P01 - Por definir', 'P01 - Por definir'),
    ('CP01 - Pagos', 'CP01 - Pagos'),
    ('CN01 - Nomina', 'CN01 - Nomina'),
    ('S01 - Sin efectos fiscales', 'S01 - Sin efectos fiscales'),
]

RUBRO_LIST = [
    ('', 'Seleccione una opción'),
    ('Aduanas', 'Aduanas'),
    ('Agronomía', 'Agronomía'),
    ('Aseguradoras', 'Aseguradoras'),
    ('Aviación', 'Aviación'),
    ('Aviación', 'Aviación'),
    ('Bebidas y tabaco', 'Bebidas y tabaco'),
    ('Comercio electrónico', 'Comercio electrónico'),
    ('Comercio general', 'Comercio general'),
    ('Construcción', 'Construcción'),
    ('Consultoría de sistemas', 'Consultoría de sistemas'),
    ('Educación', 'Educación'),
    ('Electrónica', 'Electrónica'),
    ('Fletes', 'Fletes'),
    ('Gobierno', 'Gobierno'),
    ('Industria alimenticia', 'Industria alimenticia'),
    ('Industria plástica-polietileno', 'Industria plástica-polietileno'),
    ('Manufactura', 'Manufactura'),
    ('Minería', 'Minería'),
    ('Otro', 'Otro'),
    ('Prensa', 'Prensa'),
    ('Publicidad', 'Publicidad'),
    ('Rentas', 'Rentas'),
    ('Servicios administrativos', 'Servicios administrativos'),
    ('Servicios de internet', 'Servicios de internet'),
    ('Servicios financieros', 'Servicios financieros'),
    ('Servicios públicos', 'Servicios públicos'),
    ('Tecnología de la información', 'Tecnología de la información'),
    ('Telecomunicaciones', 'Telecomunicaciones'),
    ('Textil', 'Textil'),
    ('Transporte y distribución', 'Transporte y distribución'),
    ('Turismo', 'Turismo'),
]

TIPO_OPERACION_LIST = [
    ('', 'Seleccione una opción'),
    ('Bienes', 'Bienes'),
    ('Servicios', 'Servicios'),
]

TIPO_TERCERO_LIST = [
    ('', 'Seleccione una opción'),
    ('Extranjero', 'Extranjero'),
    ('Extranjero Relacionado', 'Extranjero Relacionado'),
    ('Global', 'Global'),
    ('Nacional', 'Nacional'),
    ('Nacional Relacionado', 'Nacional Relacionado'),
]

RETENCION_IVA_LIST = [
    ('', 'Seleccione una opción'),
    ('No', 'No'),
    ('0', '0'),
    ('3%', '3%'),
    ('4%', '4%'),
    ('6%', '6%'),
    ('8%', '8%'),
    ('2/3', '2/3'),
    ('16%', '16%'),
]

RETENCION_ISR_LIST = [
    ('', 'Seleccione una opción'),
    ('No', 'No'),
    ('Si', 'Si'),
]

IVA_FRONTERA_LIST = [
    ('', 'Seleccione una opción'),
    ('No', 'No'),
    ('Si', 'Si'),
]

BANCO_LIST = [
    ('', 'Seleccione una opción'),
    ('ABC Capital S.A.', 'ABC Capital S.A.'),
    ('Acciones y Valores Banamex S.A. de C.V.', 'Acciones y Valores Banamex S.A. de C.V.'),
    ('Actinver Casa de Bolsa S.A. de C.V.', 'Actinver Casa de Bolsa S.A. de C.V.'),
    ('Akala S.A. de C.V.', 'Akala S.A. de C.V.'),
    ('American Express Bank (México) S.A.', 'American Express Bank (México) S.A.'),
    ('B y B Casa de Cambio S.A. de C.V.', 'B y B Casa de Cambio S.A. de C.V.'),
    ('Banca Afirme S.A.', 'Banca Afirme S.A.'),
    ('Banca Mifel S.A.', 'Banca Mifel S.A.'),
    ('Banco Actinver S.A.', 'Banco Actinver S.A.'),
    ('Banco Ahorro Famsa S.A.', 'Banco Ahorro Famsa S.A.'),
    ('Banco Autofin México S.A.', 'Banco Autofin México S.A.'),
    ('Banco Azteca S.A.', 'Banco Azteca S.A.'),
    ('Banco Base S.A.', 'Banco Base S.A.'),
    ('Banco Compartamos S.A.', 'Banco Compartamos S.A.'),
    ('Banco Credit Suisse (México) S.A.', 'Banco Credit Suisse (México) S.A.'),
    ('Banco del Ahorro Nacional y Servicios Financieros S.N.C. (Bansefi)', 'Banco del Ahorro Nacional y Servicios Financieros S.N.C. (Bansefi)'),
    ('Banco del Bajío S.A.', 'Banco del Bajío S.A.'),
    ('Banco Inbursa S.A.', 'Banco Inbursa S.A.'),
    ('Banco Interacciones S.A.', 'Banco Interacciones S.A.'),
    ('Banco Invex S.A.', 'Banco Invex S.A.'),
    ('Banco J.P. Morgan S.A.', 'Banco J.P. Morgan S.A.'),
    ('Banco Mercantil del Norte S.A. (Banorte)', 'Banco Mercantil del Norte S.A. (Banorte)'),
    ('Banco Monex S.A.', 'Banco Monex S.A.'),
    ('Banco Multiva S.A.', 'Banco Multiva S.A.'),
    ('Banco Nacional de Comercio Exterior S.N.C. (Bancomext)', 'Banco Nacional de Comercio Exterior S.N.C. (Bancomext)'),
    ('Banco Nacional de México S.A. (Citibanamex)', 'Banco Nacional de México S.A. (Citibanamex)'),
    ('Banco Nacional de Obras y Servicios Públicos S.N.C. (Banobras)', 'Banco Nacional de Obras y Servicios Públicos S.N.C. (Banobras)'),
    ('Banco Nacional del Ejército Fuerza Aérea y Armada S.N.C. (Banjercito)', 'Banco Nacional del Ejército Fuerza Aérea y Armada S.N.C. (Banjercito)'),
    ('Banco Regional de Monterrey S.A. (Banregio)', 'Banco Regional de Monterrey S.A. (Banregio)'),
    ('Banco Santander (México) S.A.', 'Banco Santander (México) S.A.'),
    ('Banco Ve Por Mas S.A.', 'Banco Ve Por Mas S.A.'),
    ('Banco Wal-Mart de México Adelante S.A.', 'Banco Wal-Mart de México Adelante S.A.'),
    ('BanCoppel S.A.', 'BanCoppel S.A.'),
    ('Bank of America México S.A.', 'Bank of America México S.A.'),
    ('Bank of Tokyo-Mitsubishi UFJ (México)', 'Bank of Tokyo-Mitsubishi UFJ (México)'),
    ('Bansi S.A.', 'Bansi S.A.'),
    ('Barclays Bank México S.A.', 'Barclays Bank México S.A.'),
    ('BBVA Bancomer S.A.', 'BBVA Bancomer S.A.'),
    ('Bulltick Casa de Bolsa S.A. de C.V.', 'Bulltick Casa de Bolsa S.A. de C.V.'),
    ('Casa de Bolsa Finamex S.A. de C.V.', 'Casa de Bolsa Finamex S.A. de C.V.'),
    ('Casa de Cambio Tiber S.A. de C.V.', 'Casa de Cambio Tiber S.A. de C.V.'),
    ('CI Casa de Bolsa S.A. de C.V.', 'CI Casa de Bolsa S.A. de C.V.'),
    ('CIBanco S.A.', 'CIBanco S.A.'),
    ('Cls Bank International	', 'Cls Bank International	'),
    ('Consubanco S.A.', 'Consubanco S.A.'),
    ('Deutsche Bank México S.A.', 'Deutsche Bank México S.A.'),
    ('Deutsche Securities S.A. de C.V.', 'Deutsche Securities S.A. de C.V.'),
    ('Estructuradores del Mercado de Valores Casa de Bolsa S.A. de C.V.', 'Estructuradores del Mercado de Valores Casa de Bolsa S.A. de C.V.'),
    ('Evercore Casa de Bolsa S.A. de C.V.', 'Evercore Casa de Bolsa S.A. de C.V.'),
    ('Fifth Third Bank', 'Fifth Third Bank'),
    ('Fincomún Servicios Financieros Comunitarios S.A. de C.V.', 'Fincomún Servicios Financieros Comunitarios S.A. de C.V.'),
    ('GBM Grupo Bursátil Mexicano S.A.', 'GBM Grupo Bursátil Mexicano S.A.'),
    ('HDI Seguros S.A. de C.V.', 'HDI Seguros S.A. de C.V.'),
    ('Hipotecaria Su Casita S.A. de C.V.', 'Hipotecaria Su Casita S.A. de C.V.'),
    ('HSBC México S.A.', 'HSBC México S.A.'),
    ('ING Bank (México) S.A.', 'ING Bank (México) S.A.'),
    ('Inter Banco S.A.', 'Inter Banco S.A.'),
    ('INTERCAM Banco	', 'INTERCAM Banco	'),
    ('Intercam Casa de Bolsa S.A.', 'Intercam Casa de Bolsa S.A.'),
    ('IXE Banco S.A.', 'IXE Banco S.A.'),
    ('J.P. Morgan Casa de Bolsa S.A. de C.V.', 'J.P. Morgan Casa de Bolsa S.A. de C.V.'),
    ('J.P. Morgan Chase Bank NA', 'J.P. Morgan Chase Bank NA'),
    ('J.P. SOFIEXPRESS S.A. de C.V. S.F.P.', 'J.P. SOFIEXPRESS S.A. de C.V. S.F.P.'),
    ('Kuspit Casa de Bolsa S.A. de C.V.', 'Kuspit Casa de Bolsa S.A. de C.V.'),
    ('Libertad Servicios Financieros S.A. de C.V.', 'Libertad Servicios Financieros S.A. de C.V.'),
    ('MAPFRE Tepeyac S.A.', 'MAPFRE Tepeyac S.A.'),
    ('Masari Casa de Bolsa S.A.', 'Masari Casa de Bolsa S.A.'),
    ('Merrill Lynch México S.A. de C.V.', 'Merrill Lynch México S.A. de C.V.'),
    ('Monex Casa de Bolsa S.A. de C.V.', 'Monex Casa de Bolsa S.A. de C.V.'),
    ('N/A', 'N/A'),
    ('Nacional Financiera S.A. (Nafinsa)', 'Nacional Financiera S.A. (Nafinsa)'),
    ('Operaciones Empresariales del Noreste S.A. de C.V.', 'Operaciones Empresariales del Noreste S.A. de C.V.'),
    ('OPERADORA ACTINVER S.A. DE C.V.', 'OPERADORA ACTINVER S.A. DE C.V.'),
    ('Operadora de Recursos Reforma S.A. de C.V.', 'Operadora de Recursos Reforma S.A. de C.V.'),
    ('Order Express Casa de Cambio S.A. de C.V.', 'Order Express Casa de Cambio S.A. de C.V.'),
    ('Profuturo G.N.P. S.A. de C.V.', 'Profuturo G.N.P. S.A. de C.V.'),
    ('Scotiabank Inverlat S.A.', 'Scotiabank Inverlat S.A.'),
    ('SD. Indeval S.A. de C.V.', 'SD. Indeval S.A. de C.V.'),
    ('Seguros Monterrey New York Life S.A de C.V.', 'Seguros Monterrey New York Life S.A de C.V.'),
    ('Sistema de Transferencias y Pagos STP S.A. de C.V.', 'Sistema de Transferencias y Pagos STP S.A. de C.V.'),
    ('Skandia Operadora de Fondos S.A. de C.V.', 'Skandia Operadora de Fondos S.A. de C.V.'),
    ('Skandia Vida S.A. de C.V.', 'Skandia Vida S.A. de C.V.'),
    ('Sociedad Hipotecaria Federal S.N.C.', 'Sociedad Hipotecaria Federal S.N.C.'),
    ('Solución Asea S.A. de C.V.', 'Solución Asea S.A. de C.V.'),
    ('Sterling Casa de Cambio S.A. de C.V.', 'Sterling Casa de Cambio S.A. de C.V.'),
    ('Telecomunicaciones de México', 'Telecomunicaciones de México'),
    ('The Royal Bank of Scotland México S.A.', 'The Royal Bank of Scotland México S.A.'),
    ('UBS Bank México S.A.', 'UBS Bank México S.A.'),
    ('UNAGRA S.A. de C.V. S.F.P.', 'UNAGRA S.A. de C.V. S.F.P.'),
    ('Unica Casa de Cambio S.A. de C.V.', 'Unica Casa de Cambio S.A. de C.V.'),
    ('Valores Mexicanos Casa de Bolsa S.A. de', 'Valores Mexicanos Casa de Bolsa S.A. de'),
    ('Value S.A. de C.V.', 'Value S.A. de C.V.'),
    ('Vector Casa de Bolsa S.A. de C.V.', 'Vector Casa de Bolsa S.A. de C.V.'),
    ('Volkswagen Bank S.A.', 'Volkswagen Bank S.A.'),
    ('WELLS FARGO BANK', 'WELLS FARGO BANK'),
    ('Zurich Companía de Seguros S.A. de C.V.', 'Zurich Companía de Seguros S.A. de C.V.'),
    ('Zurich Vida Companía de Seguros S.A. de C.V.', 'Zurich Vida Companía de Seguros S.A. de C.V.'),
]

MONEDA_LIST = [
    ('', 'Seleccione una opción'),
    ('MXP', 'MXP'),
    ('USD', 'USD'),
]