# Generated by Django 4.2 on 2023-06-05 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alta_materiales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='aprobadas',
        ),
        migrations.RemoveField(
            model_name='material',
            name='compras',
        ),
        migrations.RemoveField(
            model_name='material',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='material',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='material',
            name='finanzas',
        ),
        migrations.RemoveField(
            model_name='material',
            name='justificacion',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sistemas',
        ),
        migrations.RemoveField(
            model_name='material',
            name='usuario',
        ),
        migrations.CreateModel(
            name='MaterialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('justificacion', models.CharField(max_length=255)),
                ('compras', models.BooleanField(default=False)),
                ('finanzas', models.BooleanField(default=False)),
                ('sistemas', models.BooleanField(default=False)),
                ('aprobadas', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
