# Generated by Django 4.2 on 2023-06-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0003_remove_material_aprobadas_remove_material_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='id_solicitud',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AddField(
            model_name='materialsolicitud',
            name='id_solicitud',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AlterField(
            model_name='materialsolicitud',
            name='compras',
            field=models.BooleanField(default=True),
        ),
    ]
