# Generated by Django 4.2.2 on 2023-09-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0012_materialsolicitud_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsolicitud',
            name='empresa_destino',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='materialsolicitud',
            name='empresa_origen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='materialsolicitud',
            name='rfc_migracion',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
