# Generated by Django 4.2.2 on 2023-09-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0016_alter_materialsolicitud_es_migracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsolicitud',
            name='es_migracion',
            field=models.BooleanField(default=False),
        ),
    ]
