# Generated by Django 4.2.2 on 2023-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0017_alter_materialsolicitud_es_migracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsolicitud',
            name='borrador',
            field=models.BooleanField(default=False),
        ),
    ]
