# Generated by Django 4.2.2 on 2023-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0018_materialsolicitud_borrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='medida',
        ),
        migrations.AddField(
            model_name='material',
            name='alto',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='ancho',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='calibre',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='largo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='material',
            field=models.CharField(default='', max_length=20),
        ),
    ]
