# Generated by Django 4.2.2 on 2023-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0019_remove_material_medida_material_alto_material_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='alto',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='ancho',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='calibre',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='largo',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=20),
        ),
    ]
