# Generated by Django 4.2.2 on 2023-10-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0020_alter_material_alto_alter_material_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='alto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='ancho',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='calibre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='largo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='subfamilia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_alta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
