# Generated by Django 4.2.2 on 2023-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0021_alter_material_alto_alter_material_ancho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('subfamilia', models.CharField(max_length=100)),
                ('familia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producto catálogo',
                'verbose_name_plural': 'Productos catálogo',
            },
        ),
    ]
