# Generated by Django 4.2 on 2023-10-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0022_catalogomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_sat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
