# Generated by Django 4.2 on 2023-10-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0024_material_um_alto_material_um_ancho_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='tipo_producto',
            new_name='porcentaje_iva',
        ),
    ]
