# Generated by Django 4.2 on 2023-10-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0025_rename_tipo_producto_material_porcentaje_iva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='es_parte_original',
            new_name='es_mezcla',
        ),
    ]
