# Generated by Django 4.2 on 2023-10-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0026_rename_es_parte_original_material_es_mezcla'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ficha_tecnica',
            field=models.FileField(blank=True, upload_to='static/materiales/ficha_tecnica'),
        ),
        migrations.AddField(
            model_name='material',
            name='foto_producto',
            field=models.FileField(blank=True, upload_to='static/materiales/foto_producto'),
        ),
    ]
