# Generated by Django 4.2 on 2023-11-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0028_alter_material_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='porcentaje_iva',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
