# Generated by Django 4.2 on 2023-11-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0028_material_rechazado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materialsolicitud',
            name='nombre_producto_migracion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
