# Generated by Django 4.2 on 2023-11-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0030_alter_material_porcentaje_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='calibre',
        ),
        migrations.RemoveField(
            model_name='material',
            name='um_calibre',
        ),
    ]
