# Generated by Django 4.2 on 2023-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta_materiales', '0031_remove_material_calibre_remove_material_um_calibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
