# Generated by Django 4.2 on 2023-10-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar_sesion', '0010_rename_puede_comprar_customuser_puede_crear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='puede_crear',
            new_name='puede_crear_proveedor',
        ),
    ]
