# Generated by Django 4.2 on 2023-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar_sesion', '0011_rename_puede_crear_customuser_puede_crear_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='puede_crear_material',
            field=models.BooleanField(default=True),
        ),
    ]
