# Generated by Django 4.2 on 2023-11-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar_sesion', '0013_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='puede_crear_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
