# Generated by Django 4.2 on 2023-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar_sesion', '0014_customuser_puede_crear_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autorizador',
            field=models.BooleanField(default=False),
        ),
    ]
