# Generated by Django 4.2 on 2023-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar_sesion', '0015_customuser_autorizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autorizador_sustituto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requisitor',
            field=models.BooleanField(default=True),
        ),
    ]
