DEFAULT_LIST = [
    ('', 'Seleccione una opción'),
]

EMPRESA_LIST = [
    ('', 'Seleccione una opción'),
    ('Sonorg - Tago - Wichita', 'Sonorg - Tago - Wichita'),
    ('Moonrise - Wellin', 'Moonrise - Wellin'),
    ('Sonorg - Tago - Wichita - Moonrise - Wellin', 'Sonorg - Tago - Wichita - Moonrise - Wellin'),
]

EMPRESA_MIGRACION_LIST = [
    ('', 'Seleccione una opción'),
    ('Sonorg', 'Sonorg'),
    ('Tago', 'Tago'),
    ('Wichita', 'Wichita'),
    ('Moonrise', 'Moonrise'),
    ('Wellin', 'Wellin'),
]

TIPO_ALTA_LIST = [
    ('', 'Seleccione una opción'),
    ('Producto', 'Producto'),
    ('Servicio', 'Servicio'),
]

SUBFAMILIA_LIST = [
    ('', 'Seleccione una opción'),
    ('Semilla', 'Semilla'),
    ('Material cultivo', 'Material cultivo'),
    ('Orgánicos', 'Orgánicos'),
    ('Inorgánicos', 'Inorgánicos'),
    ('Orgánico-minerales', 'Orgánico-minerales'),
    ('Aminoácidos, algas marinas y extractos húmicos', 'Aminoácidos, algas marinas y extractos húmicos'),
    ('Composta', 'Composta'),
    ('Insecticidas', 'Insecticidas'),
    ('Herbicidas', 'Herbicidas'),
    ('Fungicidas', 'Fungicidas'),
    ('Bactericidas', 'Bactericidas'),
    ('Acaricidas', 'Acaricidas'),
    ('Nematicidas', 'Nematicidas'),
    ('Rodenticidas', 'Rodenticidas'),
    ('Fitorreguladores', 'Fitorreguladores'),
    ('Adherentes, sulfactantes y buferizante', 'Adherentes, sulfactantes y buferizante'),
    ('Microorganismos', 'Microorganismos'),
    ('Alguicidas', 'Alguicidas'),
    ('Feromonas y atrayentes', 'Feromonas y atrayentes'),
    ('Mejoradores de suelo', 'Mejoradores de suelo'),
    ('Control biológico', 'Control biológico'),
    ('Medio de cultivo', 'Medio de cultivo'),
    ('Materia orgánica', 'Materia orgánica'),
    ('Coadyuvantes', 'Coadyuvantes'),
    ('Químico-Inorgánico', 'Químico-Inorgánico'),
    ('Químico-Orgánico', 'Químico-Orgánico'),
    ('Insumos MR', 'Insumos MR'),
    ('Cera y sanitizantes', 'Cera y sanitizantes'),
    ('Caja', 'Caja'),
    ('Consumibles empaque', 'Consumibles empaque'),
    ('Bolsa', 'Bolsa'),
    ('Embalaje', 'Embalaje'),
    ('Etiqueta', 'Etiqueta'),
    ('Etiqueta -Fair Trade', 'Etiqueta -Fair Trade'),
    ('Etiqueta -Good Life', 'Etiqueta -Good Life'),
    ('Etiqueta -Rico Fair Trade', 'Etiqueta -Rico Fair Trade'),
    ('Etiqueta - Rico Fair', 'Etiqueta - Rico Fair'),
    ('Etiqueta - Térmicas', 'Etiqueta - Térmicas'),
    ('Etiqueta - Whole Trade', 'Etiqueta - Whole Trade'),
    ('Combustibles', 'Combustibles'),
    ('Gas', 'Gas'),
    ('Fierros y acero', 'Fierros y acero'),
    ('Herramientas', 'Herramientas'),
    ('Material eléctrico', 'Material eléctrico'),
    ('Material ferretero y tornillería', 'Material ferretero y tornillería'),
    ('Materiales de construcción', 'Materiales de construcción'),
    ('Mangueras y conexiones', 'Mangueras y conexiones'),
    ('Seguridad e higiene', 'Seguridad e higiene'),
    ('Consumibles y equipo de cómputo', 'Consumibles y equipo de cómputo'),
    ('Llantas', 'Llantas'),
    ('Mantenimiento y equipo (Filtros y refacciones)', 'Mantenimiento y equipo (Filtros y refacciones)'),
    ('Lubricantes', 'Lubricantes'),
    ('Laboratorio', 'Laboratorio'),
    ('Mobiliario y equipo menor', 'Mobiliario y equipo menor'),
    ('Papelería y artículos de oficina', 'Papelería y artículos de oficina'),
    ('Deportes', 'Deportes'),
    ('Artículos decoración, dormitorios e instalaciones', 'Artículos decoración, dormitorios e instalaciones'),
    ('Uniformes', 'Uniformes'),
    ('Empaque alimentos', 'Empaque alimentos'),
    ('Abarrotes', 'Abarrotes'),
    ('Medicamentos y materiales médicos', 'Medicamentos y materiales médicos'),
    ('Inocuidad y limpieza', 'Inocuidad y limpieza'),
    ('Fletes exportación', 'Fletes exportación'),
    ('Flete nacional', 'Flete nacional'),
    ('Paquetería', 'Paquetería'),
    ('In&Out', 'In&Out'),
    ('Gastos de exportación', 'Gastos de exportación'),
    ('Artículos publicitarios', 'Artículos publicitarios'),
    ('Marketing y publicidad', 'Marketing y publicidad'),
    ('Rentas y arrendamiento', 'Rentas y arrendamiento'),
    ('Transporte de personal', 'Transporte de personal'),
    ('Mantenimiento', 'Mantenimiento'),
    ('Seguros y fianzas', 'Seguros y fianzas'),
    ('Asesorías', 'Asesorías'),
    ('Honorarios', 'Honorarios'),
    ('Servicios generales del Campo', 'Servicios generales del Campo'),
    ('Servicios públicos', 'Servicios públicos'),
    ('Servicios al personal', 'Servicios al personal'),
    ('Servicios de comedor', 'Servicios de comedor'),
    ('Gastos Administrativos', 'Gastos Administrativos'),
    ('Plántula', 'Plántula'),
    ('Equipo de cómputo', 'Equipo de cómputo'),
    ('Maquinaria y Equipo', 'Maquinaria y Equipo'),
    ('Equipo de Transporte', 'Equipo de Transporte'),
    ('Mobiliario y Equipo de Oficina', 'Mobiliario y Equipo de Oficina'),
    ('Licencias de Software', 'Licencias de Software'),
    ('Proyectos / Construcciones en proceso', 'Proyectos / Construcciones en proceso'),
]

UNIDAD_MEDIDA_LIST = [
    ('', 'Seleccione una opción'),
    ('Kilogramo', 'Kilogramo'),
    ('Gramo', 'Gramo'),
    ('Onza', 'Onza'),
    ('Libra', 'Libra'),
    ('Litro', 'Litro'),
    ('Mililitro', 'Mililitro'),
    ('Metro cúbico', 'Metro cúbico'),
    ('Metro', 'Metro'),
    ('Centímetro', 'Centímetro'),
    ('Pie', 'Pie'),
    ('Pulgada', 'Pulgada'),
    ('Pieza', 'Pieza'),
    ('Par', 'Par'),
    ('Millar', 'Millar'),
    ('Rollo', 'Rollo'),
    ('Servicio', 'Servicio'),
    ('Paquete', 'Paquete'),
    ('Caja', 'Caja'),
    ('Tramo', 'Tramo'),
    ('Saco', 'Saco'),
    ('Galón', 'Galón'),
    ('Cubeta', 'Cubeta'),
    ('Tambo', 'Tambo'),
    ('Metro cuadrado', 'Metro cuadrado'),
    ('Kit', 'Kit'),
    ('Porron', 'Porron'),
]