DEFAULT_LIST = [
    ('', 'Seleccione una opción'),
]

EMPRESA_LIST = [
    ('', 'Seleccione una opción'),
    ('Sonorg - Tago - Wichita', 'Sonorg - Tago - Wichita'),
    ('Moonrise - Wellin', 'Moonrise - Wellin'),
    ('Sonorg - Tago - Wichita - Moonrise - Wellin', 'Sonorg - Tago - Wichita - Moonrise - Wellin'),
]

TIPO_ALTA_LIST = [
    ('', 'Seleccione una opción'),
    ('Producto', 'Producto'),
    ('Servicio', 'Servicio'),
]

SUBFAMILIA_LIST_PROVISIONAL = [
    ('', 'Seleccione una opción'),
    ('Subfamilia 1', 'Subfamilia 1'),
    ('Subfamilia 2', 'Subfamilia 2'),
    ('Subfamilia 3', 'Subfamilia 3'),
    ('Subfamilia 4', 'Subfamilia 4'),
    ('Subfamilia 5', 'Subfamilia 5'),
]

UNIDAD_MEDIDA_LIST_PROVISIONAL = [
    ('', 'Seleccione una opción'),
    ('Unidad de medida 1', 'Unidad de medida 1'),
    ('Unidad de medida 2', 'Unidad de medida 2'),
    ('Unidad de medida 3', 'Unidad de medida 3'),
    ('Unidad de medida 4', 'Unidad de medida 4'),
    ('Unidad de medida 5', 'Unidad de medida 5'),
]

TIPO_LIST = {
    'Producto': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Herramientas', 'display': 'Herramientas'},
        {'value': 'Inventario general campo', 'display': 'Inventario general campo'},
        {'value': 'Materia prima biofabrica', 'display': 'Materia prima biofabrica'},
        {'value': 'Materia prima empaque', 'display': 'Materia prima empaque'},
        {'value': 'Materia prima producción', 'display': 'Materia prima producción'},
        {'value': 'Producto acarreado', 'display': 'Producto acarreado'},
        {'value': 'Producto empacado', 'display': 'Producto empacado'},
        {'value': 'Producto terminado biofabrica', 'display': 'Producto terminado biofabrica'},
        {'value': 'Producto terminado deshidratado', 'display': 'Producto terminado deshidratado'},
    ],
    'Servicio': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Gastos comercialización y logistica', 'display': 'Gastos comercialización y logistica'},
        {'value': 'Gastos por administración', 'display': 'Gastos por administración'},
        {'value': 'Gastos por operación', 'display': 'Gastos por operación'},
        {'value': 'Ingresos por servicios', 'display': 'Ingresos por servicios'},
        {'value': 'Maquila para producción', 'display': 'Maquila para producción'},
        {'value': 'Papelería y articulos de escritorio', 'display': 'Papelería y articulos de escritorio'},
        {'value': 'Servicios generales campo', 'display': 'Servicios generales campo'},
    ],
}

FAMILIA_LIST = {
    'Herramientas': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Herramientas móviles', 'display': 'Herramientas móviles'},
    ],
    'Inventario general campo': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Inventario general campo', 'display': 'Inventario general campo'},
    ],
    'Materia prima biofabrica': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Biofabrica otros insumos', 'display': 'Biofabrica otros insumos'},
        {'value': 'Materia orgánica', 'display': 'Materia orgánica'},
        {'value': 'Microorganismos', 'display': 'Microorganismos'},
        {'value': 'Químicos', 'display': 'Químicos'},
    ],
    'Materia prima empaque': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cartón', 'display': 'Cartón'},
        {'value': 'Etiquetas', 'display': 'Etiquetas'},
        {'value': 'Insumos', 'display': 'Insumos'},
    ],
    'Materia prima producción': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Agroinsumos', 'display': 'Agroinsumos'},
        {'value': 'Agroquímicos', 'display': 'Agroquímicos'},
        {'value': 'Fertilizantes', 'display': 'Fertilizantes'},
        {'value': 'Insecticidas', 'display': 'Insecticidas'},
        {'value': 'Microorganismos', 'display': 'Microorganismos'},
        {'value': 'Plántula', 'display': 'Plántula'},
        {'value': 'Semilla', 'display': 'Semilla'},
    ],
    'Producto acarreado': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Vegetables', 'display': 'Vegetables'},
        {'value': 'Cucumber', 'display': 'Cucumber'},
        {'value': 'Dehydrated', 'display': 'Dehydrated'},
        {'value': 'Eggplant', 'display': 'Eggplant'},
        {'value': 'Green bean', 'display': 'Green bean'},
        {'value': 'Melón', 'display': 'Melón'},
        {'value': 'Pepper', 'display': 'Pepper'},
        {'value': 'Squash', 'display': 'Squash'},
    ],
    'Producto terminado biofabrica': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Bioamino', 'display': 'Bioamino'},
        {'value': 'Fert bioamino', 'display': 'Fert bioamino'},
        {'value': 'Fertilizante biofabrica', 'display': 'Fertilizante biofabrica'},
    ],
    'Producto terminado deshidratado': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Deshidratado', 'display': 'Deshidratado'},
    ],
    'Gastos comercialización y logistica': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Fletes y acarreos', 'display': 'Fletes y acarreos'},
        {'value': 'In out', 'display': 'In out'},
        {'value': 'Marketing estrategico', 'display': 'Marketing estrategico'},
    ],
    'Gastos por administración': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Gastos de oficina', 'display': 'Gastos de oficina'},
        {'value': 'Gastos financieros', 'display': 'Gastos financieros'},
        {'value': 'Gastos por mantenimiento', 'display': 'Gastos por mantenimiento'},
        {'value': 'Gastos por arrendamiento', 'display': 'Gastos por arrendamiento'},
        {'value': 'Gastos por seguros y fianzas', 'display': 'Gastos por seguros y fianzas'},
        {'value': 'Reclutamiento y seleccion', 'display': 'Reclutamiento y seleccion'},
        {'value': 'Servicios administrativos', 'display': 'Servicios administrativos'},
        {'value': 'Servicios profesionales', 'display': 'Servicios profesionales'},
    ],
    'Gastos por operación': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Análisis y laboratorio', 'display': 'Análisis y laboratorio'},
        {'value': 'Certificaciones', 'display': 'Certificaciones'},
        {'value': 'Mtto activos en campo', 'display': 'Mtto activos en campo'},
        {'value': 'Servicios de campo prorrateables', 'display': 'Servicios de campo prorrateables'},
    ],
    'Ingresos por servicios': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Distribucion y logistica', 'display': 'Distribucion y logistica'},
        {'value': 'Season settlement', 'display': 'Season settlement'},
        {'value': 'Servicios por in out', 'display': 'Servicios por in out'},
    ],
    'Maquila para producción': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Plántula', 'display': 'Plántula'},
    ],
    'Papelería y articulos de escritorio': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Papelería y articulos de escritorio', 'display': 'Papelería y articulos de escritorio'},
    ],
    'Servicios generales campo': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Servicios generales campo', 'display': 'Servicios generales campo'},
    ],
}

SUBFAMILIA_LIST = {
    'Herramientas móviles': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Equipo de cómputo', 'display': 'Equipo de cómputo'},
        {'value': 'Equipo de comunicación', 'display': 'Equipo de comunicación'},
        {'value': 'Herramientas de bombeo', 'display': 'Herramientas de bombeo'},
        {'value': 'Herramientas de medición', 'display': 'Herramientas de medición'},
        {'value': 'Herramientas eléctricas', 'display': 'Herramientas eléctricas'},
        {'value': 'Herramientas electrónicas', 'display': 'Herramientas electrónicas'},
        {'value': 'Herramientas mecánicas', 'display': 'Herramientas mecánicas'},
        {'value': 'Otros equipos', 'display': 'Otros equipos'},
    ],
    'Inventario general campo': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Artículos de higiene', 'display': 'Artículos de higiene'},
        {'value': 'Artículos de limpieza', 'display': 'Artículos de limpieza'},
        {'value': 'Combustibles & Lubricantes', 'display': 'Combustibles & Lubricantes'},
        {'value': 'Consumibles equipo de cómputo', 'display': 'Consumibles equipo de cómputo'},
        {'value': 'Equipo de seguridad', 'display': 'Equipo de seguridad'},
        {'value': 'Equipo menor de oficina', 'display': 'Equipo menor de oficina'},
        {'value': 'Filtros & Refacciones', 'display': 'Filtros & Refacciones'},
        {'value': 'Herramientas Trabajo & Cultivo', 'display': 'Herramientas Trabajo & Cultivo'},
        {'value': 'Herrería y Ferretería', 'display': 'Herrería y Ferretería'},
        {'value': 'Mangueras & Conexiones', 'display': 'Mangueras & Conexiones'},
        {'value': 'Material Eléctrico', 'display': 'Material Eléctrico'},
        {'value': 'Materiales de construcción', 'display': 'Materiales de construcción'},
        {'value': 'Materiales y consumibles de laboratorio', 'display': 'Materiales y consumibles de laboratorio'},
        {'value': 'Medicamentos y material enfermería', 'display': 'Medicamentos y material enfermería'},
        {'value': 'Pap. & Art. De Escritorio', 'display': 'Pap. & Art. De Escritorio'},
    ],
    'Biofabrica otros insumos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'BF-Otros Insumos', 'display': 'BF-Otros Insumos'},
    ],
    'Materia orgánica': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Medio de Cultivo', 'display': 'Medio de Cultivo'},
        {'value': 'Materia Orgánica', 'display': 'Materia Orgánica'},
    ],
    'Microorganismos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Microorganismos', 'display': 'Microorganismos'},
    ],
    'Químicos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Químicos', 'display': 'Químicos'},
    ],
    'Cartón': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Accesorios', 'display': 'Accesorios'},
        {'value': 'Cajas', 'display': 'Cajas'},
    ],
    'Etiquetas': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Dulcinea', 'display': 'Dulcinea'},
        {'value': 'Fair Trade', 'display': 'Fair Trade'},
        {'value': 'Good Life', 'display': 'Good Life'},
        {'value': 'Rico Fair Trade', 'display': 'Rico Fair Trade'},
        {'value': 'Rico Farms', 'display': 'Rico Farms'},
        {'value': 'Térmicas', 'display': 'Térmicas'},
        {'value': 'Whole Trade', 'display': 'Whole Trade'},
    ],
    'Insumos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Bolsa', 'display': 'Bolsa'},
        {'value': 'Embalaje', 'display': 'Embalaje'},
        {'value': 'Papel', 'display': 'Papel'},
        {'value': 'Otros Productos', 'display': 'Otros Productos'},
    ],
    'Agroinsumos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Agroinsumos', 'display': 'Agroinsumos'},
    ],
    'Agroquímicos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Agroquímicos', 'display': 'Agroquímicos'},
    ],
    'Fertilizantes': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Fertilizantes', 'display': 'Fertilizantes'},
    ],
    'Insecticidas': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': '-', 'display': '-'},
    ],
    'Plántula': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cucumber', 'display': 'Cucumber'},
        {'value': 'Eggplant', 'display': 'Eggplant'},
        {'value': 'Green Bean', 'display': 'Green Bean'},
        {'value': 'Melón', 'display': 'Melón'},
        {'value': 'Pepper', 'display': 'Pepper'},
        {'value': 'Squash', 'display': 'Squash'},
    ],
    'Semilla': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cucumber', 'display': 'Cucumber'},
        {'value': 'Eggplant', 'display': 'Eggplant'},
        {'value': 'Green Bean', 'display': 'Green Bean'},
        {'value': 'Melón', 'display': 'Melón'},
        {'value': 'Pepper', 'display': 'Pepper'},
        {'value': 'Squash', 'display': 'Squash'},
    ],
    'Vegetables': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cucumber', 'display': 'Cucumber'},
        {'value': 'Eggplant', 'display': 'Eggplant'},
        {'value': 'Green Bean', 'display': 'Green Bean'},
        {'value': 'Melón', 'display': 'Melón'},
        {'value': 'Pepper', 'display': 'Pepper'},
        {'value': 'Squash', 'display': 'Squash'},
    ],
    'Cucumber': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'English / European', 'display': 'English / European'},
        {'value': 'Persian', 'display': 'Persian'},
        {'value': 'Pickle', 'display': 'Pickle'},
        {'value': 'Slicer / American', 'display': 'Slicer / American'},
    ],
    'Dehydrated': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cucumber', 'display': 'Cucumber'},
        {'value': 'Eggplant', 'display': 'Eggplant'},
        {'value': 'Green Bean', 'display': 'Green Bean'},
        {'value': 'Melón', 'display': 'Melón'},
        {'value': 'Pepper', 'display': 'Pepper'},
        {'value': 'Squash', 'display': 'Squash'},
    ],
    'Eggplant': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Barcelona', 'display': 'Barcelona'},
        {'value': 'Eggplant', 'display': 'Eggplant'},
        {'value': 'Night Shadow', 'display': 'Night Shadow'},
    ],
    'Green bean': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Green Bean', 'display': 'Green Bean'},
    ],
    'Melón': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cantaloupe', 'display': 'Cantaloupe'},
        {'value': 'Honeydew', 'display': 'Honeydew'},
        {'value': 'Mini Seedless', 'display': 'Mini Seedless'},
        {'value': 'Orange Flesh', 'display': 'Orange Flesh'},
        {'value': 'Seedless', 'display': 'Seedless'},
    ],
    'Pepper': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Anaheim', 'display': 'Anaheim'},
        {'value': 'Cayenne', 'display': 'Cayenne'},
        {'value': 'Green Bell Pepper', 'display': 'Green Bell Pepper'},
        {'value': 'Jalapeño', 'display': 'Jalapeño'},
        {'value': 'Orange Bell Pepper', 'display': 'Orange Bell Pepper'},
        {'value': 'Poblano', 'display': 'Poblano'},
        {'value': 'Red Bell Pepper', 'display': 'Red Bell Pepper'},
        {'value': 'Serrano', 'display': 'Serrano'},
        {'value': 'Yellow Bell Pepper', 'display': 'Yellow Bell Pepper'},
    ],
    'Squash': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Acorn', 'display': 'Acorn'},
        {'value': 'Butterking', 'display': 'Butterking'},
        {'value': 'Butternut', 'display': 'Butternut'},
        {'value': 'Delicata', 'display': 'Delicata'},
        {'value': 'Kabocha', 'display': 'Kabocha'},
        {'value': 'Spaghetti', 'display': 'Spaghetti'},
        {'value': 'Sugar Pie', 'display': 'Sugar Pie'},
        {'value': 'Yellow', 'display': 'Yellow'},
        {'value': 'Zucchini', 'display': 'Zucchini'},
    ],
    'Bioamino': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Bioamino', 'display': 'Bioamino'},
    ],
    'Fert bioamino': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Fert-Bioamino', 'display': 'Fert-Bioamino'},
    ],
    'Fertilizante biofabrica': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Potasio', 'display': 'Potasio'},
    ],
    'Deshidratado': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Pastas', 'display': 'Pastas'},
        {'value': 'Snacks', 'display': 'Snacks'},
    ],
    'Fletes y acarreos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Fletes de Exportación', 'display': 'Fletes de Exportación'},
        {'value': 'Fletes de Importación', 'display': 'Fletes de Importación'},
        {'value': 'Maniobras', 'display': 'Maniobras'},
    ],
    'In out': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'In&Out', 'display': 'In&Out'},
    ],
    'Marketing estrategico': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Marketing', 'display': 'Marketing'},
    ],
    'Gastos de oficina': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Gastos Generales de Oficina', 'display': 'Gastos Generales de Oficina'},
    ],
    'Gastos financieros': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Comisiones e Intereses', 'display': 'Comisiones e Intereses'},
    ],
    'Gastos por mantenimiento': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Mantenimiento equipo de computo', 'display': 'Mantenimiento equipo de computo'},
        {'value': 'Mantenimiento a equipos de transporte', 'display': 'Mantenimiento a equipos de transporte'},
        {'value': 'Mtto Mob y Eq de Oficina', 'display': 'Mtto Mob y Eq de Oficina'},
        {'value': 'Gastos mantenimiento edificios y construcciones', 'display': 'Gastos mantenimiento edificios y construcciones'},
    ],
    'Gastos por arrendamiento': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Arrendamiento Eq de Transporte', 'display': 'Arrendamiento Eq de Transporte'},
        {'value': 'Renta de Oficina', 'display': 'Renta de Oficina'},
        {'value': 'Renta de impresoras oficina', 'display': 'Renta de impresoras oficina'},
    ],
    'Gastos por seguros y fianzas': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Gtos por seguros & fianzas', 'display': 'Gtos por seguros & fianzas'},
    ],
    'Reclutamiento y seleccion': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Gastos por reclutamiento', 'display': 'Gastos por reclutamiento'},
    ],
    'Servicios administrativos': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Relativos al personal', 'display': 'Relativos al personal'},
        {'value': 'Servicios de TI', 'display': 'Servicios de TI'},
    ],
    'Servicios profesionales': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Auditorias', 'display': 'Auditorias'},
        {'value': 'Consultorias', 'display': 'Consultorias'},
    ],
    'Análisis y laboratorio': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Análisis Clínicos', 'display': 'Análisis Clínicos'},
        {'value': 'Cromatográficos', 'display': 'Cromatográficos'},
        {'value': 'Fertilidad / Fisico-Quimicos', 'display': 'Fertilidad / Fisico-Quimicos'},
        {'value': 'Fitopatología / Microbiología', 'display': 'Fitopatología / Microbiología'},
        {'value': 'Squash', 'display': 'Squash'},
    ],
    'Certificaciones': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Permisos derechos y certificaciones', 'display': 'Permisos derechos y certificaciones'},
    ],
    'Mtto activos en campo': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Mtto Construcciones & Edificios', 'display': 'Mtto Construcciones & Edificios'},
        {'value': 'Mtto Eq. de Transporte', 'display': 'Mtto Eq. de Transporte'},
        {'value': 'Mtto Maquinaria & Equipo', 'display': 'Mtto Maquinaria & Equipo'},
        {'value': 'Mtto Mob & Eq. de Oficina', 'display': 'Mtto Mob & Eq. de Oficina'},
    ],
    'Servicios de campo prorrateables': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Relativos a la Operacion en Campo', 'display': 'Relativos a la Operacion en Campo'},
        {'value': 'Relativos al Personal de Campo', 'display': 'Relativos al Personal de Campo'},
        {'value': 'Servicio de arrendamiento', 'display': 'Servicio de arrendamiento'},
    ],
    'Distribucion y logistica': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Distribucion & Logistica', 'display': 'Distribucion & Logistica'},
    ],
    'Season settlement': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Season Settlement', 'display': 'Season Settlement'},
    ],
    'Servicios por in out': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Cooling Services', 'display': 'Cooling Services'},
    ],
    'Papelería y articulos de escritorio': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Pap & Art de Escritorio', 'display': 'Pap & Art de Escritorio'},
    ],
    'Servicios generales campo': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Servicios Generales Campo', 'display': 'Servicios Generales Campo'},
        {'value': 'Uniformes y accesorios', 'display': 'Uniformes y accesorios'},
    ],
}

UNIDAD_MEDIDA_LIST = {
    'Producto': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': '24 piezas', 'display': '24 piezas'},
        {'value': 'Activo Fijo', 'display': 'Activo Fijo'},
        {'value': 'Análisis', 'display': 'Análisis'},
        {'value': '"Bin24"""', 'display': '"Bin24"""'},
        {'value': '"Bin36"""', 'display': '"Bin36"""'},
        {'value': 'Bolsa', 'display': 'Bolsa'},
        {'value': 'Bulto', 'display': 'Bulto'},
        {'value': 'Caja', 'display': 'Caja'},
        {'value': 'Caja de Campo', 'display': 'Caja de Campo'},
        {'value': 'Caja de Plástico', 'display': 'Caja de Plástico'},
        {'value': 'Caja Pre-Enfrío', 'display': 'Caja Pre-Enfrío'},
        {'value': 'Centímetro', 'display': 'Centímetro'},
        {'value': 'Cubeta', 'display': 'Cubeta'},
        {'value': 'Dosis', 'display': 'Dosis'},
        {'value': 'Galón', 'display': 'Galón'},
        {'value': 'Gramo', 'display': 'Gramo'},
        {'value': 'Hectárea', 'display': 'Hectárea'},
        {'value': 'Kilogramo', 'display': 'Kilogramo'},
        {'value': 'Kit', 'display': 'Kit'},
        {'value': 'Libra', 'display': 'Libra'},
        {'value': 'Liquidación', 'display': 'Liquidación'},
        {'value': 'Litro', 'display': 'Litro'},
        {'value': 'Lote', 'display': 'Lote'},
        {'value': 'Metro', 'display': 'Metro'},
        {'value': 'Metro Cuadrado', 'display': 'Metro Cuadrado'},
        {'value': 'Metro Cubico', 'display': 'Metro Cubico'},
        {'value': 'Mililitro', 'display': 'Mililitro'},
        {'value': 'Milla', 'display': 'Milla'},
        {'value': 'Millar', 'display': 'Millar'},
        {'value': 'Onza', 'display': 'Onza'},
        {'value': 'Par', 'display': 'Par'},
        {'value': 'Pie', 'display': 'Pie'},
        {'value': 'Pieza', 'display': 'Pieza'},
        {'value': 'Porrón', 'display': 'Porrón'},
        {'value': 'Pulgada', 'display': 'Pulgada'},
        {'value': 'Rollo', 'display': 'Rollo'},
        {'value': 'Saco', 'display': 'Saco'},
        {'value': 'Tambo', 'display': 'Tambo'},
        {'value': 'Tonelada', 'display': 'Tonelada'},
        {'value': 'Unidad', 'display': 'Unidad'},
        {'value': 'Unidades de Azufre', 'display': 'Unidades de Azufre'},
        {'value': 'Unidades de Boro', 'display': 'Unidades de Boro'},
        {'value': 'Unidades de Calcio', 'display': 'Unidades de Calcio'},
        {'value': 'Unidades de Cloro', 'display': 'Unidades de Cloro'},
        {'value': 'Unidades de Cobre', 'display': 'Unidades de Cobre'},
        {'value': 'Unidades de Fierro', 'display': 'Unidades de Fierro'},
        {'value': 'Unidades de Fósforo', 'display': 'Unidades de Fósforo'},
        {'value': 'Unidades de Magnesio', 'display': 'Unidades de Magnesio'},
        {'value': 'Unidades de Manganeso', 'display': 'Unidades de Manganeso'},
        {'value': 'Unidades de Molibdeno', 'display': 'Unidades de Molibdeno'},
        {'value': 'Unidades de Nitrógeno', 'display': 'Unidades de Nitrógeno'},
        {'value': 'Unidades de Potasio', 'display': 'Unidades de Potasio'},
        {'value': 'Unidades de Silicio', 'display': 'Unidades de Silicio'},
        {'value': 'Unidades de Zinc', 'display': 'Unidades de Zinc'},
        {'value': 'Yarda', 'display': 'Yarda'},
    ],
    'Servicio': [
        {'value': '', 'display': 'Seleccione una opción'},
        {'value': 'Servicio', 'display': 'Servicio'},
    ],
}
